name: CI Pipeline Tianguistore

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  backend-tests:
    runs-on: ubuntu-latest

    #Todos los comandos 'run' se ejecutaran dentro de la carpeta backend
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.0.0'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Instalar depencias
        run: npm ci || npm install

      - name: Ejecutar pruebas
        run: npm test -if-present
      
      - name: Run linter
        run: npm run lint -if-present